  
name: Run Tenping API

on:
  push:
    branches:
      - main
# on:
#      schedule:
#          - cron: "0 */2 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.x
              uses: actions/setup-python@v1
              with:
                  python-version: "3.8"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Tenping API Program
              run: |
                  python "autopost.py"
            - name: Commits
              run: |
                  git config --local user.email "king199777@gmail.com"
                  git config --local user.name "Auto_Crawler_Name"
                  git add .
                  git commit -m "Auto - Post Success"
            - name: Push
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: "main"
